//* USER ACTIONS
export const SET_USER_AUTH = 'SET_USER_AUTH';

export const DEL_USER_AUTH = 'DEL_USER_AUTH';

//* POST ACTIONS

export const SET_CITY_KEYWORD = 'SET_CITY_KEYWORD';

export const SET_ALL_POSTS = 'SET_ALL_POSTS';

export const POST_UPDATE_STATUS = 'POST_UPDATE_STATUS';

export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const NEXT_PAGE_POSTS = 'NEXT_PAGE_POSTS';

export const UPDATE_POST = 'UPDATE_POST';

export const ADD_NEW_POST = 'ADD_NEW_POST';

export const DELETE_POST = 'DELETE_POST';

//* TELEPORT ACTIONS
export const SET_ALL_CONTS = 'SET_ALL_CONT';

export const SELECT_CONT = 'SELECT_CONT';

export const SET_URBAN_OPTION = 'SET_URBAN_OPTION';

export const SELECT_URBAN = 'SELECT_URBAN';

export const CLEAR_URBAN = 'CLEAR_URBAN';
